
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import io
import os


from pathlib import Path
import vision_demo
from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage,  filedialog as fd, font as font



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

# img = PhotoImage(file="googleVSBACK.jpg")
#canvas.create_image(0,0, image = img)
canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    989.0,
    fill="#808080",
    outline="")


def select_file():
    
    filetypes=[('Images','*.jpg *.jpeg *.png')]
    filename = fd.askopenfilename(
        initialdir='/',
        filetypes=filetypes)


    vision_demo.main_call(filename)

myFont = font.Font(family='NunitoSans Regular')   
myFont = font.Font(size=20)

fileOpen = Button( window,text = "Select File" , fg = "#FFFFFF" , width =25, height= 5 ,bg="#eb4c42",command = lambda : select_file())
fileOpen['font'] = myFont

canvas.create_rectangle(
    528.0,
    589.0,
    912.0,
    753.0,
    fill="#eb4c42",
    outline="")

canvas.create_text(
    433.0,
    302.0,
    anchor="nw",
    text="Easy Invoice Extract",
    fill="#FFFFFF",
    font=("NunitoSans Regular", 64 * -1)
)
fileOpen.place(x=525, y=590)

canvas.create_text(
    617.0,
    639.0,
    anchor="nw",
    text="select file",
    fill="#FFFFFF",
    font=("NunitoSans Regular", 48 * -1)
)


window.resizable(False, False)
window.mainloop()
